FROM node:20-alpine
WORKDIR /app
COPY frontend/package.json /app/package.json
COPY frontend/vite.config.js /app/vite.config.js
COPY frontend/.env /app/.env
RUN npm install --no-audit --no-fund
COPY frontend /app
EXPOSE 5173
CMD [ "npm", "run", "dev" ]
